import type { Metadata } from "next";
import "./globals.css";
import { Gilroy, Mazius } from "./fonts/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Gilroy.variable} ${Mazius.variable}`}>
        {children}
      </body>
    </html>
  );
}
